// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace Repository.Migrations.MariaDb
{
    [DbContext(typeof(MariaDbContext))]
    [Migration("20220606145548_MariaDb")]
    partial class MariaDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Contact", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("Username")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("last")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("lastdate")
                        .HasColumnType("datetime");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<string>("server")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("Username");

                    b.ToTable("ContactDB");
                });

            modelBuilder.Entity("Domain.Message", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Contactid")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("content")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created")
                        .HasColumnType("datetime");

                    b.Property<bool>("sent")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("id");

                    b.HasIndex("Contactid");

                    b.ToTable("MessageDB");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Nickname")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.HasKey("Username");

                    b.ToTable("UserDB");
                });

            modelBuilder.Entity("Domain.Contact", b =>
                {
                    b.HasOne("Domain.User", null)
                        .WithMany("contacts")
                        .HasForeignKey("Username");
                });

            modelBuilder.Entity("Domain.Message", b =>
                {
                    b.HasOne("Domain.Contact", null)
                        .WithMany("messages")
                        .HasForeignKey("Contactid");
                });

            modelBuilder.Entity("Domain.Contact", b =>
                {
                    b.Navigation("messages");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Navigation("contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
